spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vote_db?useUnicode=true&useTimezone=GMT+8
    username: vote
    password: vote123
    druid:
      initial-size: 1
      max-active: 10
      validation-query: select 1
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: true
          statement-close-after-log-enabled: true
          result-set-open-after-log-enabled: true
          result-set-close-after-log-enabled: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 500
        wall:
          enabled: true
          config:
            delete-allow: false
  jpa:
    database: mysql
    show-sql: true
logging:
  level:
    org:
      springframework: debug